name: Push CI

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: Codecademy/run-on-yarn@v1
      - run: yarn ${{ matrix.command }}

    strategy:
      fail-fast: false
      matrix:
        command: ['build', 'compile', 'format:verify', 'lint', 'test:ci']

on: push
